### ISSUE TITLE
Redaction de la page Persona dans wiki

### ISSUE THREAD

**Issue by omly97** [omly97/Lyproject2018#1]
Pour l'inclusion des images, j'ai créé un dossier Mes-photos dans lequel j'ai mis mes images et que j'ai ensuite envoyer dans mon repository. Le probleme c'est que je ne parviens pas  à les inclure. Vous pouvez voir la page Persona

**Comment by moussadiallo** [comment]
C'est bien, j'ai fait un test avec une de tes images et apparement ça marche, il faut juste s'assurer que le lien de l'image est bon
